routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function () {
    Route::middleware(['auth:admin'])->group(function () {
        Route::get('/', 'AdminController@index')->name('admin.dashboard');
    });
    Route::middleware(['guest:admin'])->group(function () {
        Route::get('/login', 'AdminController@showLoginForm')->name('admin.login');
        Route::post('/login', 'AdminController@login')->name('admin.login.submit');
        Route::get('/register', 'AdminController@showRegisterForm')->name('admin.register');
        Route::post('/register', 'AdminController@register')->name('admin.register.submit');

        Route::get('password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');;
        Route::get('password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('admin.password.reset');;
        Route::post('password/reset', 'AdminResetPasswordController@reset');


    });
    Route::get('/logout', 'AdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::resource('/setting', 'SettingController');
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::prefix('/dashboard')->group(function(){
        Route::get('/lineChart', 'DashboardController@lineChart');


    });
    Route::prefix('/notification')->group(function(){
        Route::get('/', 'NotificationController@index')->name('admin.notificationList');
        Route::get('/delete/{id}', 'NotificationController@delete')->name('admin.notification.delete');
        Route::get('/changeStatus/{id}', 'NotificationController@changeStatus')->name('admin.notification.changeStatus');

    });



    Route::get('/profile', 'ProfileController@index')->name('admin.profile');
    Route::post('/profile', 'ProfileController@update')->name('admin.profile.update');

    Route::resource('/court', 'CourtController');

    Route::resource('/time_schedule', 'TimeScheduleController');
    Route::resource('/court_booking', 'CourtBookingController');
    Route::resource('/courtSchedule', 'CourtScheduleController');
    Route::post('/courtSchedule/setTime', 'CourtScheduleController@setTime')->name('admin.setTime');
    Route::get('/usersList', 'UserController@usersList')->name('admin.usersList');
    Route::get('/showUserCourtBooked/{id}', 'UserController@showUserCourtBooked')->name('admin.showUserCourtBooked');
    Route::get('/usersChangeStatus/{id}/{status}', 'UserController@usersChangeStatus')->name('admin.usersChangeStatus');
    Route::get('/usersCourtsReservation', 'UserController@usersCourtsReservation')->name('admin.usersCourtsReservation');
    Route::get('/userDelete/{id}', 'UserController@delete')->name('admin.userDelete');
    Route::get('/deleteUserCourtBooked/{id}/{booked_id}', 'UserController@deleteUserCourtBooked')->name('admin.deleteUserCourtBooked');

});


Route::group(['namespace' => 'Web'], function () {
    Route::post('/bookingCourt', 'BookingController@bookingCourt')->name('web.bookingCourt');


    Route::get('/', 'HomeController@index')->name('web.home');
    Route::get('/viewCourt', 'HomeController@viewCourt')->name('web.viewCourt');
    Route::post('/ajax_selected_court/{id}', 'HomeController@ajax_selected_court');
    Route::get('/ajaxSelectCourtSchedule/{date}', 'HomeController@ajaxSelectCourtSchedule');

    Route::middleware(['auth:web'])->group(function () {

        Route::get('/accountSetting', 'AccountSettingController@showAccountSettingForm')->name('web.accountSetting');
        Route::post('/accountSetting/update', 'AccountSettingController@updateAccountSetting')->name('web.updateAccountSetting');

        Route::get('/bookingCourtList', 'BookingController@bookingCourtList')->name('web.bookingCourtList');
        Route::get('/userReservationTypeList/{type}', 'BookingController@userReservationTypeList')->name('web.userReservationTypeList');

        Route::get('/showUserCourtBooked/{id}', 'BookingController@showUserCourtBooked')->name('web.showUserCourtBooked');
//        Route::get('/printUserCourtBooked','BookingController@printUserCourtBooked')->name('web.printUserCourtBooked');

        Route::get('/removeCourt/{id}', 'BookingController@removeCourt')->name('web.removeCourt');


    });
    Route::middleware(['guest:web'])->group(function () {
        Route::post('/ajaxLogin', 'HomeController@ajaxLogin')->name('web.ajaxLogin');
    });


});

app/Time_schedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Time_schedule extends Model
{
    protected $table='time_schedules';
    protected $fillable=['start_hour','end_hour','court_schedule_id','price'];
    public function time_schedule_courts(){
        return $this->hasMany('App\Time_schedule_court','time_schedule_id');
    }
}

app/Http/Controllers/Admin/TimeScheduleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Time_schedule;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Traits\Shared;

class TimeScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $data;
    use Shared;

    public function __construct()
    {
        //Traits
        $this->data['getSetting'] = $this->getSetting();
        $this->data['bookingNotification'] = $this->getUserNotifications();
        $this->data['countUserNotifications'] = $this->countNotification();
        //end Traits
        $this->data['title'] = 'Time Schedule';

    }
    public function index()
    {

        $start_hour='';
        $end_hour='';
        $timeSchedules=Time_schedule::all();
        foreach($timeSchedules as $i=> $time_schedule){
            if($i==0){
                $start_hour=$time_schedule['start_hour'];
            }

            $last_key=(count($timeSchedules)-1);
            if($i==$last_key){
                $end_hour=$time_schedule['end_hour'];
            }
            $this->data['start_hour']= $start_hour;
            $this->data['end_hour']= $end_hour;




        }

        return view('admin.time_schedule.list', $this->data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [

            'start_hour' => 'required',
            'end_hour' => 'required|greater_than_field:start_hour',
        ],['end_hour.greater_than_field'=>'End Hour must be Greater than Start hour']);
        $formInput = $request->all();



        DB::table('time_schedules')->delete();

        for ($i = $formInput['start_hour']; $i < $formInput['end_hour']; $i++) {


           Time_schedule::create(['start_hour'=>$i.":00",'end_hour'=>($i+1).':00']);

        }

        return redirect('admin/time_schedule');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/time_schedule/list.blade.php
@extends('layouts.admin')

@section('content')


<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>@isset($title){{$title}}@endisset</h3>
        </div>


    </div>

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_content">
                    <div class="row">


                        <div class="col-md-6">
                            <ul>
                                <li>Start Hour:@isset($start_hour){{date("g:i A", strtotime($start_hour))}}@endisset
                                </li>
                                <li>End Hour:@isset($end_hour){{date("g:i A", strtotime($end_hour))}}@endisset</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            @include('alertMessages')
                            <form action="{{route('time_schedule.store')}}" method="post"
                                  enctype=multipatr/form-data>
                                {{ csrf_field() }}


                                <div class="form-group">

                                    <label for="court_times">Court Time</label>

                                    <div class="row">
                                        <div
                                            class=" col-md-4 form-group{{ $errors->has('start_hour') ? ' has-error' : '' }}">
                                            <select name="start_hour" class="form-control ">

                                                @isset($end_hour)
                                                <option value="{{str_replace(':00','',$start_hour)}}" readonly selected>
                                                    {{date("g:i A",
                                                    strtotime($start_hour))}}
                                                </option>
                                                @else
                                                <option value="0" disabled selected>select start hour</option>
                                                @endisset
                                                @include('admin.time_schedule')


                                            </select>
                                            @if ($errors->has('start_hour'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('start_hour') }}</strong>
                                    </span>
                                            @endif
                                        </div>


                                        <div
                                            class=" col-md-4 form-group{{ $errors->has('end_hour') ? ' has-error' : '' }}">
                                            <select name="end_hour" class="form-control ">

                                                @isset($end_hour)
                                                <option value="{{str_replace(':00','',$end_hour)}}" readonly selected>
                                                    {{date("g:i A",
                                                    strtotime($end_hour))}}
                                                </option>
                                                @else
                                                <option value="0" disabled selected>select start hour</option>
                                                @endisset
                                                @include('admin.time_schedule')


                                            </select>
                                            @if ($errors->has('end_hour'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('end_hour') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>


                                </div>


                                <div class="form-group">
                                    <button class="btn btn-primary mr15" type="submit">Save Changes</button>

                                </div>

                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@push('scripts')
<script>
    $('#timeScheduleTable').DataTable({
        processing: true,


    });
</script>

@endpush