routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function () {
    Route::middleware(['auth:admin'])->group(function () {
        Route::get('/', 'AdminController@index')->name('admin.dashboard');
    });
    Route::middleware(['guest:admin'])->group(function () {
        Route::get('/login', 'AdminController@showLoginForm')->name('admin.login');
        Route::post('/login', 'AdminController@login')->name('admin.login.submit');
        Route::get('/register', 'AdminController@showRegisterForm')->name('admin.register');
        Route::post('/register', 'AdminController@register')->name('admin.register.submit');

        Route::get('password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');;
        Route::get('password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('admin.password.reset');;
        Route::post('password/reset', 'AdminResetPasswordController@reset');


    });
    Route::get('/logout', 'AdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::resource('/setting', 'SettingController');
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::prefix('/dashboard')->group(function(){
        Route::get('/lineChart', 'DashboardController@lineChart');


    });
    Route::prefix('/notification')->group(function(){
        Route::get('/', 'NotificationController@index')->name('admin.notificationList');
        Route::get('/delete/{id}', 'NotificationController@delete')->name('admin.notification.delete');
        Route::get('/changeStatus/{id}', 'NotificationController@changeStatus')->name('admin.notification.changeStatus');

    });



    Route::get('/profile', 'ProfileController@index')->name('admin.profile');
    Route::post('/profile', 'ProfileController@update')->name('admin.profile.update');

    Route::resource('/court', 'CourtController');

    Route::resource('/time_schedule', 'TimeScheduleController');
    Route::resource('/court_booking', 'CourtBookingController');
    Route::resource('/courtSchedule', 'CourtScheduleController');
    Route::post('/courtSchedule/setTime', 'CourtScheduleController@setTime')->name('admin.setTime');
    Route::get('/usersList', 'UserController@usersList')->name('admin.usersList');
    Route::get('/showUserCourtBooked/{id}', 'UserController@showUserCourtBooked')->name('admin.showUserCourtBooked');
    Route::get('/usersChangeStatus/{id}/{status}', 'UserController@usersChangeStatus')->name('admin.usersChangeStatus');
    Route::get('/usersCourtsReservation', 'UserController@usersCourtsReservation')->name('admin.usersCourtsReservation');
    Route::get('/userDelete/{id}', 'UserController@delete')->name('admin.userDelete');
    Route::get('/deleteUserCourtBooked/{id}/{booked_id}', 'UserController@deleteUserCourtBooked')->name('admin.deleteUserCourtBooked');

});


Route::group(['namespace' => 'Web'], function () {
    Route::post('/bookingCourt', 'BookingController@bookingCourt')->name('web.bookingCourt');


    Route::get('/', 'HomeController@index')->name('web.home');
    Route::get('/viewCourt', 'HomeController@viewCourt')->name('web.viewCourt');
    Route::post('/ajax_selected_court/{id}', 'HomeController@ajax_selected_court');
    Route::get('/ajaxSelectCourtSchedule/{date}', 'HomeController@ajaxSelectCourtSchedule');

    Route::middleware(['auth:web'])->group(function () {

        Route::get('/accountSetting', 'AccountSettingController@showAccountSettingForm')->name('web.accountSetting');
        Route::post('/accountSetting/update', 'AccountSettingController@updateAccountSetting')->name('web.updateAccountSetting');

        Route::get('/bookingCourtList', 'BookingController@bookingCourtList')->name('web.bookingCourtList');
        Route::get('/userReservationTypeList/{type}', 'BookingController@userReservationTypeList')->name('web.userReservationTypeList');

        Route::get('/showUserCourtBooked/{id}', 'BookingController@showUserCourtBooked')->name('web.showUserCourtBooked');
//        Route::get('/printUserCourtBooked','BookingController@printUserCourtBooked')->name('web.printUserCourtBooked');

        Route::get('/removeCourt/{id}', 'BookingController@removeCourt')->name('web.removeCourt');


    });
    Route::middleware(['guest:web'])->group(function () {
        Route::post('/ajaxLogin', 'HomeController@ajaxLogin')->name('web.ajaxLogin');
    });


});

resources/views/admin/include/footer.blade.php
<div style="text-align: center">
   Copyright of @ 2018 <a href="{{url('/')}}">{{$getSetting ? $getSetting['website_name'] : " Template"}}</a>
</div>
<div class="clearfix"></div>

resources/views/admin/include/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{$getSetting ? $getSetting['website_name'] : " Template"}} | @isset($title){{$title }}@endisset </title>

    <!-- Bootstrap -->
    <link href="{{asset('adminTemplate/asset/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('adminTemplate/asset/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('adminTemplate/asset/nprogress/nprogress.css')}}" rel="stylesheet">
    <link href="{{asset('adminTemplate/asset/datatables/datatables.css')}}" rel="stylesheet">
    <link href="{{asset('shared/loading.css')}}" rel="stylesheet">
    <!--    datePicker-->
<!--    <link rel="stylesheet" href="{{asset('adminTemplate/asset/datePicker/bootstrap-datepicker.css')}}">-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.standalone.css">


    <!-- Custom Theme Style -->
    <link href="{{asset('adminTemplate/build/css/custom.css')}}" rel="stylesheet">
    <!-- jQuery -->
    <script src="{{asset('adminTemplate/asset/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap -->
    <script src="{{asset('adminTemplate/asset/bootstrap/dist/js/bootstrap.min.js')}}"></script>


    @stack('styles')
</head>

resources/views/admin/include/nav_menu.blade.php
<div class="nav_menu">
    <nav>
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                   aria-expanded="false">
                    <img src="{{asset('images/ss.jpg')}}" alt="">{{Auth::user()->name}}
                    <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{{url('admin/profile')}}"> Profile</a></li>
                    <li>
                        <a href="{{url('admin/setting')}}">

                            <span>Settings</span>
                        </a>
                    </li>

                    <li><a href="{{route('admin.logout')}}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                </ul>
            </li>

            <li role="presentation" class="dropdown">
                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                   aria-expanded="false">
                    <i class="fa fa-globe fa-5x"></i>
                    <span
                        class="badge bg-green"> @isset($countUserNotifications){{$countUserNotifications}}@endisset</span>
                </a>
                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <div class="notification">
                        @isset($bookingNotification)
                        @foreach($bookingNotification as $notification)
                        <li class="notificationStatus" data-id="{{$notification['id']}}">
                            <a href="#">

                        <span>
                          <span style="color:#000; font-weight: bold">{{$notification['user']['name']}}</span>
                          <span class="time">{{$notification->updated_at->diffForHumans()}}</span>
                        </span>
                        <span class="message">
                         <span class="label {{($notification['status']=='read') ? 'label-success':'label-danger'}}">{{$notification['status']}}</span>
                            {{$notification['court_names']}} at {{$notification['times']}} on {{$notification['dates']}}
                        </span>
                            </a>
                        </li>



                        @endforeach
                        @endisset

                    </div>
                    <li>

                        <div class="text-center">
                            <a href="{{route('admin.notificationList')}}">
                                <strong>See All Notifications</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>

                </ul>

            </li>
        </ul>
    </nav>
</div>

resources/views/admin/include/sidebar.blade.php
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>{{$getSetting ? $getSetting['website_name'] : " Template"}}</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            <img src="{{asset('images/ss.jpg')}}" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>Welcome,</span>

            <h2>{{Auth::user()->name}}</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
                <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-home"></i> Dashboard </span></a>


                <li><a><i class="fa fa-futbol-o"></i> Courts Management <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{route('court.index')}}"><i class="fa fa-home"></i> Courts </span></a>
                        <li><a href="{{route('courtSchedule.index')}}"><i class="fa fa-calendar"></i> Court Schedule </span></a>
<!--                        <li><a href="{{route('court_booking.index')}}"><i class="fa fa-home"></i> Courts Booking Status </span></a>-->
                    </ul>
                </li>

                <li><a><i class="fa fa-users"></i> Users Management  <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{route('admin.usersList')}}"><i class="fa fa-users"></i>Users</span></a>
                        <li><a href="{{route('admin.usersCourtsReservation')}}"><i class="fa fa-users"></i>Users Courts Reservation</span></a>

                    </ul>
                </li>
            </ul>





        </div>


    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a href="{{url('admin/setting/')}}" data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{route('admin.logout')}}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>